### ISSUE TITLE
Тестирование "не экспортных" методов

### ISSUE THREAD

**Issue by Segate-ekb** [bia-technologies/yaxunit#10]
В ряде модулей существует необходимость тестировать не только программный интерфейс, но и отдельные процедуры модуля, которые не несут нагрузки вне этого модуля, а значит делать их экспортными не имеет смысла.
В то же время для полноценного покрытия сложного модуля, с ограниченным программным интерфейсом, тестами - потребуется большое их количество.

Предлагаю сделать возможным поиск тестов не только в модулях созданных самостоятельно в расширении, но и в модулях которые расширяют какой либо объект проверяемой конфигурации.
Например вот так:
![image](https://user-images.githubusercontent.com/80944823/201831914-5dcee675-925a-4e6a-8de7-439bc53f3113.png)
таким образом можно получить доступ к тестированию отдельных процедур и функций, и тем самым уменьшить и упростить юниты для тестирования.

**Comment by asosnoviy** [comment]
Если я правильно понял проблему, то в расширении делаете неэкспортные методы экспортными и покрываете как экспортные

**Comment by alkoleft** [comment]
@asosnoviy Я иначе понял желание.

Импортируем себе модуль.
Размещаем в нем метод "ИсполняемыеСценарии" и тестируем в нем приватные методы.
Но у такого подхода есть как минимум один нюанс, имя теста должно быть <> имени тестируемого метода, а то в рекурсию упадем

**Comment by alkoleft** [comment]
И еще один момент, который не нравиться, расширяя объекты мы расширяем интерфейс объекта. Что может стрельнуть.
