### ISSUE TITLE
Утверждения. Описать особенности поведения "Свойство"

### ISSUE THREAD

**Issue by alkoleft** [bia-technologies/yaxunit#107]
Описать особенности поведения "Свойство"/ "Элемент" и прочее.

Описать в доке и описании методов

**Comment by 1cgh** [comment]
@alkoleft  Что-то вот такое:

Методы Свойство() и Элемент() переключают объект проверки для последующих методов-утверждений. Они будут применяться к значению свойства или элементу коллекции. Но не переключает сам контекст на это значение, а всегда применяется к исходному объекту, помещенному в ОжидаетЧто().
Например: имеется ПроверяемыйОбъект, являющийся массивом. Элементы массива - структуры со свойством ВложенныйМассив. В значении этого свойства - массив. И стоит задача проверить длину массива в свойстве ВложенныйМассив в элементе массива ПроверяемыйОбъект с индексом 3.

Правильно:
```bsl
ЮТест.ОжидаетЧто(ПроверяемыйОбъект)
    .Свойство("[3].ВложенныйМассив")
        .ИмеетДлину(ОжидаемаяДлина)
;
```
Неправильно:
```bsl
ЮТест.ОжидаетЧто(ПроверяемыйОбъект)
    .Элемент(3)
        .Свойство("ВложенныйМассив")
            .ИмеетДлину(ОжидаемаяДлина)
;
```
