### ISSUE TITLE
Запуск тестов из конфигурации

### ISSUE THREAD

**Issue by antonsm2011** [bia-technologies/yaxunit#109]
Прошу добавить возможность запускать тесты из общих модулей в конфигурации.
Для тех, кто пользуется хранилищами (я в их числе), это поможет не добавлять еще одно хранилище расширения и следить за тем, чтобы конфигурация соответствовала тестам в расширении.

**Comment by sokolov-rv** [comment]
п.1 - отдавать тесты прямо в конфе такое себе. Плюс покрытие тестами кода обычно считают - и тут надо тестовые модули еще покрывать

п.4 - Мы наоборот еще прописали защиту от запуска расширения на рабочей базе. Вдруг кто-то "борзый" решит случайно / специально подключить расширение на рабочую базу и там погонять тесты.
