### ISSUE TITLE
Не проходит тест проверки количества вызовов метода

### ISSUE THREAD

**Issue by dlyubanevich** [bia-technologies/yaxunit#113]
У меня возникла следующая ситуация, которую я не знаю пока как побороть.

Есть метод общего модуля, вызов которого я хочу протестировать в одном тесте несколько раз исходя из вариантов.

```1c-enterprise
Процедура Тест() Экспорт

    // Подготовка тестового окружения

    Варианты = ЮТест.Варианты("Отказ")
         .Добавить(Истина)
         .Добавить(Ложь);

    Мокито.Обучение(ОбщийМодуль2)
       .Когда("МетодКогдаОтказ")
       .Вернуть(1)
       .Когда("МетодКогдаНеОтказ")
       .Вернуть(0)
       .Прогон();
    
    Для Каждого Вариант Из Варианты.СписокВариантов() Цикл
    
       // Вызов тестируемого сценария
    
       ОбщийМодуль1.НекоторыйМетод(Вариант.Отказ);
    
       // Проверка поведения и результатов
    
       Если Вариант.Отказ Тогда
    
           Мокито.Проверить(ОбщийМодуль2)
              .КоличествоВызовов("МетодКогдаОтказ")
              .Равно(1);
    
       Иначе
    
          Мокито.Проверить(ОбщийМодуль2)
              .КоличествоВызовов("МетодКогдаНеОтказ")
              .Равно(1);
    
       КонецЕсли;
    
    КонецЦикла;

КонецПроцедуры
```

Тест падает: 
_Ожидали, что проверяемое значение  - вызовы метода `ОбщийМодуль(Общий Модуль).МетодКогдаНеОтказ`, имеет длину (размер) `1`, но это не так._

Проблема в том, что `ОбщийМодуль1.НекоторыйМетод` добавлен в расширение и этот метод доступен для мокирования (в каких-нибудь других тестах), **но в этом тесте он не мокируется**, однако тест не проходит как раз из-за анализа вызова.

```1c-enterprise
&Вместо("НекоторыйМетод")
Процедура ЮТНекоторыйМетод(Отказ) Экспорт
	
   ИмяМетода = "НекоторыйМетод";
   ПараметрыМетода = Мокито.МассивПараметров(Отказ);
   ПрерватьВыполнение = Ложь;

   Мокито.АнализВызова(
    	ОбщийМодуль1, 
    	ИмяМетода,
    	ПараметрыМетода, 
    	ПрерватьВыполнение
    );

    Если Не ПрерватьВыполнение Тогда
       ПродолжитьВызов(Отказ); 
    КонецЕсли;
	
КонецПроцедуры
```

Код тестируемого метода:

```1c-enterprise
Процедура НекоторыйМетод(Отказ) Экспорт
	
   Если Отказ Тогда
       ОбщийМодуль2.МетодКогдаОтказ();
   Иначе
       ОбщийМодуль2.МетодКогдаНеОтказ();
   КонецЕсли;
	
КонецПроцедуры
```

Получается, что при первом вызове процедуры `ОбщийМодуль1.НекоторыйМетод `режим работы мокито = [Тестирование] и переменная `ПрерватьВыполнение = Ложь`. Но при выполнении метода `Мокито.Проверить` устанавливается режим работы [Проверка] и в этом случае при повторном вызове процедуры `ОбщийМодуль1.НекоторыйМетод`, переменная `ПрерватьВыполнение = Истина`.
`Мокито.Сбросить()` не помогает, т.к. полностью сбрасывает все настройки мокирования.

Кроме как спускать обучение в цикл и добавить в конце цикла `Мокито.Сбросить()` я вариантов не вижу.
Но корректное ли это поведение в целом?

**Comment by alkoleft** [comment]
Не знаю актуально ли еще, для решения проблемы вам необходимо в цикле вызывать метод `Мокито.Прогон`, он переводит в мокито "боевой" режим.

```bsl
    Для Каждого Вариант Из Варианты.СписокВариантов() Цикл

      Мокито.Прогон();
       // Вызов тестируемого сценария
    
       ОбщийМодуль1.НекоторыйМетод(Вариант.Отказ);
    
       // Проверка поведения и результатов
    
       Если Вариант.Отказ Тогда
    
           Мокито.Проверить(ОбщийМодуль2)
              .КоличествоВызовов("МетодКогдаОтказ")
              .Равно(1);
    
       Иначе
    
          Мокито.Проверить(ОбщийМодуль2)
              .КоличествоВызовов("МетодКогдаНеОтказ")
              .Равно(1);
    
       КонецЕсли;
    
    КонецЦикла;
```

**Comment by dlyubanevich** [comment]
Спасибо.
