### ISSUE TITLE
Тесты не выполняются на англоязычной базе

### ISSUE THREAD

**Issue by sulfur17** [bia-technologies/yaxunit#127]
потому что в модуле приложения переопределяется процедура ПриНачалеРаботыСистемы, а в англоязычной базе она называется OnStart.

**Comment by sulfur17** [comment]
еще обработка ЮТHTTPСервисЗапрос имеет только русские свойства и методы, надо добавить английские и организовать работу с ними

**Comment by alkoleft** [comment]
Поддержку английского тогда надо везде добавлять и скорее всего, чтобы не засорять, надо делать несколько билдов

**Comment by sulfur17** [comment]
я этим занимаюсь и пока получается в одном билде все сделать.
Скоро допишу и предложу мерж реквест.

**Comment by sulfur17** [comment]
@alkoleft так мы решили что поддержку английского делать не будем, правильно? Надо закрыть задачу тогда

**Comment by theshadowco** [comment]
Лучше разносить изменения - английский делать отдельным реквестом

**Comment by alkoleft** [comment]
В этой задаче предлагаю сделать, чтобы движок работал в конфигурациях с английским языком кода (свойство ScriptVariant).

Перевод API/UI сделать отдельно.

**Comment by alkoleft** [comment]
@sulfur17 Когда ждать реквест?

**Comment by sulfur17** [comment]
не скоро) Если надо срочно то лучше поручить кому-то другому, я не могу быстро это сделать

**Comment by alkoleft** [comment]
Пока потребность только у вас)

**Comment by sulfur17** [comment]
у меня потребности больше нет, я с английской 1С больше не работаю, задачу закрываю
