### ISSUE TITLE
Ошибка в методе ЮТУтверждения.НеВыбрасываетИсключение

### ISSUE THREAD

**Issue by sulfur17** [bia-technologies/yaxunit#131]
такой код выдает ошибку
```bsl
ЮТест.ОжидаетЧто(Ответ)
	.ИмеетТип(Тип("HTTPСервисОтвет"))
	.Свойство("КодСостояния").Равно(200)
	.Метод("ПолучитьТелоКакСтроку").НеВыбрасываетИсключение()

```
т.к. в строке функции НеВыбрасываетИсключение()
```bsl
Модуль = ПроверяемоеЗначение(Контекст);
```
ПроверяемоеЗначение возвращает 200, а не модуль

**Comment by alkoleft** [comment]
Просто оставлю это здесь. https://bia-technologies.github.io/yaxunit/api/%D0%AE%D0%A2%D0%A3%D1%82%D0%B2%D0%B5%D1%80%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F#%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE
