### ISSUE TITLE
добавить возможность получать случайное значение перечисления

### ISSUE THREAD

**Issue by sulfur17** [bia-technologies/yaxunit#132]
предлагаю добавить возможность получать случайное значение перечисления/справочника и т.д. \
Например так: \
`ЮТТестовыеДанные.СлучайноеЗначениеИзСписка(Перечисления.ТипыКомпонентов)`

**Comment by alkoleft** [comment]
Давно хочу вынести в отдельный метода API

**Comment by alexandr-yang** [comment]
У меня есть наработки по этой теме, могу доработать и поделиться

**Comment by sokolov-rv** [comment]
Предложение: для функции получения случайного значения перечисления можно добавить параметр типа массив "мВыбранныеЗначения"
 - если параметр пустой -> возвращаем случайно из всех значений
 - если параметр массив -> возвращаем случайно из значений массива

**Comment by alkoleft** [comment]
> если параметр массив -> возвращаем случайно из значений массива
Уже есть метод получения случайного значения массива ЮТТестовыеДанные.СлучайноеЗначениеИзСписка
