### ISSUE TITLE
Добавить в ассерты и предикаты поддержку проверки по регулярному выражению

### ISSUE THREAD

**Issue by Daabramov** [bia-technologies/yaxunit#138]
Хотелось бы иметь в ассертах и предикат нечто подобное

`Ютест.ОжидаетЧто("курс 75.11").СоответствуетШаблону("\D*\s\d{2}\.\d{2}")`

**Comment by alkoleft** [comment]
В задаче #136 я реализую подключение и установку компонент на клиент.
