### ISSUE TITLE
Зависимость от СтроковыеФункцииКлиентСервер

### ISSUE THREAD

**Issue by KrapivinAndrey** [bia-technologies/yaxunit#14]
Единственная внешняя зависимость - которую можно просто включить в модуль ЮТОбщий

**Comment by nixel2007** [comment]
Или взять отдельным модулем. Благо лицензия позволяет.

**Comment by igostv** [comment]
Сделал на время изучения вот так:
`СтрСоединить(Новый Массив(Уровень * 4 + 1), " ")`

**Comment by theshadowco** [comment]
поправим сегодня-завтра, чет забыли запушить правки в паблик
