### ISSUE TITLE
Не запускаются тесты в обычном приложении

### ISSUE THREAD

**Issue by alexandr-yang** [bia-technologies/yaxunit#16]
При открытии формы `СозданиеНастройки` возникает ошибка:

![image](https://user-images.githubusercontent.com/1947592/213884601-d4b36fc1-dadf-40f2-b11d-79d07714882c.png)

Так же не отрабатывает параметр запуска `RunUnitTests`.

В конфигураторе проблема решается копированием кода из модуля управляемого приложения в модуль обычного приложения. Но так как расширение разробатывается на EDT, там нет доступа к этому модулю (по крайней мере я не нашел). Как вариант, можно просто подсунуть файл OrdinaryApplicationModule.bsl, но не уверен что расширение соберется.

**Comment by theshadowco** [comment]
Я думаю, что для обычного приложения и другие приколы могут быть. Мы не тестировали в данном режиме, посмотрим, что можно сделать

**Comment by igostv** [comment]
Толстый клиент управляемое приложение тоже не работает
