### ISSUE TITLE
Утверждения для проверки исключений методов выполнять в транзакции

### ISSUE THREAD

**Issue by alkoleft** [bia-technologies/yaxunit#172]
При тестировании проверок проведения документа необходимо, чтобы сам тест не был в транзакции (проверки отменяют транзакцию и следующая проверка упадет).

При написании и ошибках теста могу создаваться неудаляемые данные, избежать этого можно если проверку на исключение обернуть в транзакцию.

```bsl
Документ = Документы.Документ1.СоздатьДокумент();
ЗаполнитьДокумент(Документ)
Ютест.ОжидаетЧто(Документ).Метод("Записать").Параметр(РежимЗаписиДокумента.Проведение).ВыбрасываетИсключение();
ЗаполнитьДокументИначе(Документ)
Ютест.ОжидаетЧто(Документ).Метод("Записать").Параметр(РежимЗаписиДокумента.Проведение).ВыбрасываетИсключение();
```

В этом случае после теста в системе останутся тестовые данные.

Добавить в метод ВыбрасываетИсключение параметр управления транзакцией, а вызов метода обернуть в транзакцию.

Бывают и более сложные методы генерирующие данные.

**Comment by potoyalo** [comment]
Докину пару кейсов:
- Цикл по `ЮТест.Варианты(...)` внутри теста
- Проверка `ЮТест.ОжидаетЧтоТаблицаБазы(...)` после тестируемого исключения, которое отменило транзакцию

**Comment by alkoleft** [comment]
@potoyalo Создание и отмена транзакции в `ВыбрасываетИсключение` будет выполнятся если уже нет транзакции выше.

Так, что думаю указанные кейсы не сломает.
Плюс будет флаг регулирующий использование транзакции..
