### ISSUE TITLE
Добавить метод генерации случайного номера телефона

### ISSUE THREAD

**Issue by alkoleft** [bia-technologies/yaxunit#175]
Добавить метод генерации случайного номера телефона с возможностью указывать код страны.

**Comment by sokolov-rv** [comment]
Если можно - закрепите за мной, хочу научиться делать пулл-реквесты в этот проект. 
Будет супер, если есть дока как дойти до пулл-реквеста.

**Comment by alkoleft** [comment]
@sokolov-rv Есть черновик доки https://github.com/bia-technologies/yaxunit/blob/feature/125/documentation/contributing/index.md
