### ISSUE TITLE
Мокито для методов расширения

### ISSUE THREAD

**Issue by LevkinSergey** [bia-technologies/yaxunit#18]
Есть ли какая-то методология/примеры/возможность для мокирования методов, разработанных в расширении.

Сейчас для мокирования метода его нужно добавить в тестовое расширение. Методы одного расширения сейчас нельзя переопределить в другом. 

Подскажите как это можно обойти?

**Comment by theshadowco** [comment]
Адекватных предложений нет

**Comment by LevkinSergey** [comment]
Я вот тоже думал и ничего не придумал.

**Comment by alkoleft** [comment]
Возможно в будущем, если осилим кодогенерацию при деплое в базу 1с, а сейчас это невозможно
