### ISSUE TITLE
Доработать утверждения ИБ для проверки строк неограниченной длины

### ISSUE THREAD

**Issue by berlinsky-nk** [bia-technologies/yaxunit#187]
https://github.com/bia-technologies/yaxunit/blob/67e287eb804810a279ba10d0dd5fa28650bdd3de/exts/yaxunit/src/CommonModules/%D0%AE%D0%A2%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D1%8B%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%A1%D0%B5%D1%80%D0%B2%D0%B5%D1%80/Module.bsl#L49C7-L49C8

Например, после определения шаблона:
```		
		Если ТипЗнч(ВыражениеПредиката.Значение) = Тип("Строка") Тогда
			Шаблон = СтрЗаменить(Шаблон, "%1", СтрШаблон("ПОДСТРОКА(%%1, 1, %1)", Формат(СтрДлина(ВыражениеПредиката.Значение) + 1, "ЧГ=")));
		КонецЕсли;
```

Чтобы не приходилось писать так:
```
			.Реквизит("ПОДСТРОКА(Сообщение, 1, 1000)").Равно(Сообщение)
```

**Comment by berlinsky-nk** [comment]
+ сюда же

в утверждения ИБ добавить пачку `Между*()`

**Comment by alkoleft** [comment]
> + сюда же
> 
> в утверждения ИБ добавить пачку `Между*()`

Вынес в отдельно #221
