### ISSUE TITLE
Тесты движка создают и не удаляют данные в справочнике Товары

### ISSUE THREAD

**Issue by SeiOkami** [bia-technologies/yaxunit#197]
Проблема в том, что, к примеру, при загрузке данных их макета внутри теста, созданные ссылки не добавляются в удаляемые тестовые данные. Они считают, что в глобальном контексте
![image](https://github.com/SeiOkami/yaxunit/assets/42138875/8366144e-304a-4bf6-9d86-c33be64119e4)

Движок теряет контекст исполнения:

![image](https://github.com/SeiOkami/yaxunit/assets/42138875/877f59cd-873a-457f-b05d-f86dc5e6f847)

ЮТНастройкиВыполнения[80]

**Comment by SeiOkami** [comment]
Движок после создания ссылки пытается проверить нужно ли добавлять её в удаляемые тестовые данные. И смотрит свойства не конектста теста\набора, а глобального. Хотя находится в тесте

**Comment by alkoleft** [comment]
Исправлено, теперь контексты сервера и клиента синхронизируются, доработано в #316
