### ISSUE TITLE
ЮТСравнениеКлиентСервер.ЗначениеСвойства не умеет получать свойство коллекции субконто регистра БУ

### ISSUE THREAD

**Issue by SeiOkami** [bia-technologies/yaxunit#201]
У регистра БУ есть особенность. Свойство коллекции Субконто нельзя получить по Коллекция["Имя"], а нужно по Коллекция.Имя

![image](https://github.com/bia-technologies/yaxunit/assets/42138875/daf1da20-2c1d-4dd0-9429-0720b7e8f589)
![image](https://github.com/bia-technologies/yaxunit/assets/42138875/e327b64e-2e5f-4327-ac8c-d254035c93a7)

**Comment by alkoleft** [comment]
Похоже на какую-то особенность платформы. Нужен костыль)
