### ISSUE TITLE
Метод по заполнению ТЗ из строки MarkDown

### ISSUE THREAD

**Issue by SeiOkami** [bia-technologies/yaxunit#202]
Сейчас есть метод, который возвращает массив структур с ключами по строке.

Но иногда удобно получить именно таблицу значений (с методами поиска, свертки, возможностью передать в запрос и так далее).

И иногда бывает нужно сделать колонку нужного типа. Например, числом или датой

Я когда-то делал подобное: https://fastcode.im/Templates/8290

**Comment by alkoleft** [comment]
Возможно подойдет https://bia-technologies.github.io/yaxunit/docs/user-api/test-data/#%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8%D0%B7-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2

**Comment by alkoleft** [comment]
@SeiOkami Предложение выше не подходит?

**Comment by SeiOkami** [comment]
> @SeiOkami Предложение выше не подходит?

Блин, теперь я понял, что гитхаб мне оповещенки всё это время присылал... Попробую, спасибо
