### ISSUE TITLE
Реализовать в движке функциональность установки управляемых блокировок в отдельном сеансе (относительно сеанса теста)

### ISSUE THREAD

**Issue by marusov** [bia-technologies/yaxunit#225]
```
Процедура МойТест()
...
ЮТест.УправляемыеБлокировки()
.Установить(ОписаниеБлокировки)
.Длительность(30)
.Заблокировать()
;

ДальшеКодМоегоТеста(); // Должен или упасть по таймауту блокировки или корректно дождаться (в зависимости от условий теста)
```

Как вариант реализации, запускать служебное фоновое задание, в котором по описанию устанавливать блокировку и выставлять паузу() на завершение метода фонового задания

**Comment by alkoleft** [comment]
Не забыть убивать ФЗ после завершения теста.

**Comment by theshadowco** [comment]
@marusov , а тебе в каком сценарии это требуется? Многопользовательский режим эмулировать хочешь?

**Comment by marusov** [comment]
@theshadowco Что-то типа того, но если быть точнее тестировать поведение с учетом возможных ожиданий на блокировках. Например, проверять что при параллельной записи мы не создадим дубли или "корректно" упадем при таймауте блокировки. Чтобы полноценно эмулировать многопользовательский режим - только управления блокировками будет недостаточно - для этого еще нужно будет научиться запускать "конкурентные" тесты параллельно, да еще и с обратной связью между сеансами, чтобы синхронизировать (контролировать) моменты блокировок
