### ISSUE TITLE
Проверка форматированных строк

### ISSUE THREAD

**Issue by SeiOkami** [bia-technologies/yaxunit#245]
Строковые методы платформы позволяют работать и с форматированными строками
Сейчас движок ругается. 

Например, здесь в Представлении форматированная строка

![image](https://github.com/bia-technologies/yaxunit/assets/42138875/adb71518-0d78-4e8d-b24a-a580aa3076d2)

Движок выдает ошибку:  

> Не верный тип проверяемого значения (`Форматированная строка`), должен быть `Строка`

Предлагаю перед проверкой на строку допускать и форматированные

**Comment by alkoleft** [comment]
Уже реализовано в последнем релизе #199
