### ISSUE TITLE
Добавить метод для получения случайного значения предопределенных данных

### ISSUE THREAD

**Issue by 1cgh** [bia-technologies/yaxunit#246]
Добавить метод для получения случайного значения предопределенных данных для планов видов расчета, планов видов характеристик, планов счетов и справочников.

Насколько я понимаю, то список для выбора надо получать запросом, чтобы выбирать из реально существующих значений. Да и через Метаданные вроде не получить список, заданный в конфигураторе.

А дальше уже просто выбираем случайное значение.

Открытый вопрос: что делать, если предопределенных значений нет. Возвращать пустую ссылку или падать?

**Comment by alexandr-yang** [comment]
> Да и через Метаданные вроде не получить список, заданный в конфигураторе.
Метаданные.Справочники.Номенклатура.ПолучитьИменаПредопределенных()

**Comment by 1cgh** [comment]
Ага, почему-то пропустил этот метод. Но я бы все равно получал запросом только реально существующие ссылки, учитывая что обновление предопределенных может быть настроено по-разному и по имени из метаданных предопределенного значения может и не быть в базе

**Comment by 1cgh** [comment]
Также нужен аналогичный метод для групп. Они тоже могут быть предопределенными

**Comment by alkoleft** [comment]
> Ага, почему-то пропустил этот метод. Но я бы все равно получал запросом только реально существующие ссылки, учитывая что обновление предопределенных может быть настроено по-разному и по имени из метаданных предопределенного значения может и не быть в базе

Тут другая проблема скрывается, натыкался не раз. 
1. Тесты выполняются в транзакции 
2. Во время теста будет выполнено обновление предопределенных данных, созданы недостающие.
3. После отката транзакции элементы удалятся и при обращении к ним возникнет ошибка.

**Comment by alkoleft** [comment]
> Также нужен аналогичный метод для групп. Они тоже могут быть предопределенными

Насчет метода - сомнения, думаю лучше добавить условия отбора. `СлучайноеПредопределенноеЗначение(Справочник, Новый Структура("ЭтоГруппа, Родитель", Истина, ПустаяСсылка));`

**Comment by 1cgh** [comment]
@alkoleft при получении запросом я предлагаю просто выбирать элементы с заполненным ИмяПредопределенныхДанных
и уже потом из них выбирать случайное. в метаданные не ползать совсем за именами предопределенных, а выбирать только те, которые есть фактически в базе
По поводу отбора, а не двух методов, согласен. Тоже уже думал, что может понадобиться выбор еще и в рамках родителя.
