### ISSUE TITLE
Конструктор для создания тестовых данных

### ISSUE THREAD

**Issue by alkoleft** [bia-technologies/yaxunit#25]
Есть идея упростить создание тестовых данных.

```bsl
	Запись = ЮТест.Данные().КонструкторОбъекта(Документы.ПриходТовара);
	
	Запись.Фикция("Организация")
		.Фикция("Поставщик")
		.Фикция("Склад")
		.ТабличнаяЧасть("Товары");
	
	ТоварныеЗапасы = ЮТест.Данные().Коллекция("ВидДвижения, Склад, Товар, Количество");
	
	ДанныеОбъекта = Запись.ДанныеОбъекта();
	
	Для Инд = 1 По 3 Цикл
		
		Запись.ДобавитьСтроку()
			.Фикция("Товар")
			.Фикция("Количество")
			.Фикция("Цена")
			.Установить("Сумма", Запись.ДанныеСтроки().Количество * Запись.ДанныеСтроки().Цена);
		
		ДанныеСтроки = Запись.ДанныеСтроки();
		
		ТоварныеЗапасы.Добавить(ВидДвиженияНакопления.Приход, ДанныеОбъекта.Склад, ДанныеСтроки.Товар, ДанныеСтроки.Количество);
		
	КонецЦикла;
	
	Док = Запись.Провести(Истина);
	
	ЮТест.ОжидаетЧто(Док.Движения.ТоварныеЗапасы)
		.Равно(ТоварныеЗапасы);
```

Конструктор объекта на основании текучих выражений умеет:
* `Фикция` - на основании менеджера и имени переданного реквизита определяет тип реквизита и устанавливает случайное значение (СлучайноеЧисло, ЮТест.Данные().СоздатьЭлемент и тд)
* `ТабличнаяЧасть`, `ДобавитьСтроку` - позволяет заполнять данные ТЧ
* `ДанныеСтроки`, `ДанныеОбъекта` - позволяют обращаться к заполняемым данным, для получения значений реквизитов
* `Провести`, `Записать` - сохраняет данные и возвращает ссылку или объект
* Работает как на сервере так и на клиенте.

Что скажете?

**Comment by asosnoviy** [comment]
Четко сформулировать не могу. Но не нравиться цикл

**Comment by asosnoviy** [comment]
> Четко сформулировать не могу. Но не нравиться цикл

Догнал. Цикл тут просто так. И все можно флюентом.

**Comment by asosnoviy** [comment]
ГлаголОтФикцияОбязательные() - Заполнить все обязательные поля фикциями

**Comment by alkoleft** [comment]
> ГлаголОтФикцияОбязательные() - Заполнить все обязательные поля фикциями

Да, такое тоже планируется
