### ISSUE TITLE
Предикаты. Утверждение для коллекции противоположное ЛюбойЭлементСоответствуетПредикату 

### ISSUE THREAD

**Issue by theshadowco** [bia-technologies/yaxunit#260]
Иногда нужно убедиться что в коллекции (в таблице значений в частности) нет ни одной строки по условию нескольких полей (например при провеедении убедиться отсутствии строк с отрицальным поступлением)

**Comment by alkoleft** [comment]
Для этих целей подойдет утверждение ЮТест.ОжидаетЧТо().НеСодержит(Предикат)
