### ISSUE TITLE
Доработка документации. Сбор предложений

### ISSUE THREAD

**Issue by alkoleft** [bia-technologies/yaxunit#265]
Собираю здесь предложения по доработке документации.

Если в документации плохо раскрыт какой-то момент/блок, либо чего то не хватает напишите об этом здесь.

Любые другие ваши пожелания касательно документации также можете оставить здесь

**Comment by theshadowco** [comment]
1. Добавить описание подключения своих  модулей с подсписками
2. Добавить описание подписки "Инициализация"

**Comment by alkoleft** [comment]
Реализовано в релизе [24.03](https://github.com/bia-technologies/yaxunit/releases/tag/24.04)
