### ISSUE TITLE
В програмный интерфейс ЮТест добавить ЮТТесты

### ISSUE THREAD

**Issue by asosnoviy** [bia-technologies/yaxunit#27]
Чтобы в модуле теста вызывать только одним общий модуль ЮТест.

```
ЮТест.Тесты().ДобавитьТест();
ЮТест.Данные().СоздатьЭлемент();
ЮТест.ОжидаетЧто()

```

**Comment by alkoleft** [comment]
`ЮТест` - идеологически предоставляет доступ к объектам/методам используемым на этапе исполнения

`ЮТТесты ` имеет другое назначение - регистрация тестов перед исполнением.

Также сейчас плагин в EDT отслеживает вызов ЮТТесты для поиска зарегистрированных тестов.
