### ISSUE TITLE
[BUG] Ошибка при проверке цепочки вызовов Мокито

### ISSUE THREAD

**Issue by alexandr-yang** [bia-technologies/yaxunit#297]
**Версия движка**
24.02

**Версия платформы**
8.3.22.1923

**Описание ошибки**
При проверке цепочки вызовов Мокито возникает ошибка исполнения: `Недостаточно фактических параметров`.
Связана она с тем, что отличается сигнатура методов `Мокито.Проверить(Объект, Описание = Неопределено) `и `МокитоПроверки.Проверить(Объект, Описание)`

**Пример кода**
```bsl
Мокито
    .Проверить(ОбщийМодуль1)
        .КоличествоВызовов("Метод1").Равно(1)
    .Проверить(ОбщийМодуль2)
        .КоличествоВызовов("Метод2").Равно(1);
```

**Comment by theshadowco** [comment]
При указанном примере кода ошибки быть не может - ошибка возникнет только если вызвать метод `МокитоПроверки.Проверить(Объект)`

**Comment by alexandr-yang** [comment]
Ошибка есть. Потому что метод Равно возвращает МокитоПроверки и дальше вызывается метод Проверить

**Comment by theshadowco** [comment]
нда, недоработка

**Comment by theshadowco** [comment]
По хорошему, надо в `Равно` возвращать `Мокито`

**Comment by theshadowco** [comment]
а может и нет...

**Comment by theshadowco** [comment]
> > По хорошему, надо в `Равно` возвращать `Мокито`
> 
> Не согласен, в этом случаи при каждом вызове `Проверить` будет станавливаться режим, что является избыточным

Да, согласен, я поторопился с предложением
