### ISSUE TITLE
Сайт проекта на Github Pages

### ISSUE THREAD

**Issue by otymko** [bia-technologies/yaxunit#3]
Читать документацию из отдельных файлов хорошо. Но хотелось бы иметь удобный поиск только по документации. Предлагаю опубликовать docs + readme на Github Pages, например, в формате  Docusaurus или MkDocs .

**Comment by otymko** [comment]
@theshadowco чего думаешь? Я могу сделать на досуге.

**Comment by theshadowco** [comment]
@otymko 
Согласен, буду благодарен

**Comment by theshadowco** [comment]
ga скрипт надо добавить и ссылку в основнуб ридмишку

**Comment by theshadowco** [comment]
И ссылки поправить на глагне
