### ISSUE TITLE
[Bug]: Не работает формат выбода ошибки HTML на Mac

### ISSUE THREAD

**Issue by alexandr-yang** [bia-technologies/yaxunit#319]
### 🐞 Описание ошибки

<img width="863" alt="image" src="https://github.com/bia-technologies/yaxunit/assets/1947592/7a8ae630-2321-462f-8eb2-6760bcf1b7a2">

### Версия YaxUnit

24.03

### Версия 1С:Предприятие

8.3.24.1368

### Операционная система

Mac

**Comment by alkoleft** [comment]
К сожалению нет Mac для воспроизведения проблемы.

Судя по скрину есть еще проблемы со шрифтами и svg иконками в таблице
