### ISSUE TITLE
Выдавать ошибку при заполнении несуществующего реквизита через ЮТестовыеДанные

### ISSUE THREAD

**Issue by KovAlexey** [bia-technologies/yaxunit#323]
## Описание сценария (кейса) использования, применения
Сейчас, в случае если ошибся в имени реквизита, никаких ошибок не происходит.
Что приводит к относительно труднодиагностируемым проблемам.
Хотелось бы поменять это поведением, но сделать параметризируемым, т.к. полагаю есть сценарии, для каких-нибудь универсальных обработок заполнения.

## Вариант реализации новой функциональности
Предлагаю по умолчанию при установке свойства проверять наличие реквизита у заполняемого объекта.
Если свойства нет - выдавать исключение.
Так же добавить возможность не выдавать исключение в случаях, где это необходимо

## Дополнительная информация
https://t.me/BIAOpenTools/12/2887
По этому обсуждению

**Comment by alkoleft** [comment]
Если речь про конструктор объекта, что я добавил проверки в релизе 24.03.
Сейчас как раз люди поймали ошибку https://t.me/BIAOpenTools/12/3319

**Comment by KovAlexey** [comment]
Понял, не обновился оказывается.
Тогда закрываю
