### ISSUE TITLE
[Bug]: При вызове исключения в ПередТестовымНабором() ошибка нигде не отражается, а тесты набора находятся в статусе Ожидание

### ISSUE THREAD

**Issue by 1cgh** [bia-technologies/yaxunit#332]
### 🐞 Описание ошибки

Добавить тестовый набор и тесты в него.
Создать процедуру ПередТестовымНабором(), в ней добавить вызов исключения.
Запустить тесты набора.
Тесты не выполнятся и будут в статусе Ожидание.
Информация об исключении нигде не отображается (ну кроме ЖР).

ПослеТестовогоНабора не чекал. Возможно, там такая же история.

### Версия YaxUnit

24.03

### Версия 1С:Предприятие

8.3.22.2411

### Операционная система

Windows

**Comment by alkoleft** [comment]
Для разработки используется EDT или конфигуратор?

**Comment by 1cgh** [comment]
Разработка в ЕДТ, но статус так отображается в обработке запуска в режиме предприятия. Сегодня позднее чекну, что будет если через плагин из едт запустить. И ПослеТестовогоНабора заодно

**Comment by alkoleft** [comment]
В EDT ошибка должна падать на наборы
