### ISSUE TITLE
[Bug]: В логе не отражается вызов Перед После

### ISSUE THREAD

**Issue by zeegin** [bia-technologies/yaxunit#345]
### 🐞 Описание ошибки

Сабж
Неполноценный лог, сложнее анализировать

**Comment by alkoleft** [comment]
Выводит, или о чем речь?

![image](https://github.com/bia-technologies/yaxunit/assets/13838250/e970c386-33c2-45a3-b578-75175d4accee)

**Comment by alkoleft** [comment]
![image](https://github.com/bia-technologies/yaxunit/assets/13838250/5df09194-e0b9-47a8-9b0c-7e304b323806)

В файл аналигично.
