### ISSUE TITLE
[NEW] Комбинация значений для конструктора вариантов

### ISSUE THREAD

**Issue by alexandr-yang** [bia-technologies/yaxunit#349]
## Описание сценария (кейса) использования, применения
В некоторых случаях необходимо сгенерировать комбинацию вариантов.

В текущей реализации это можно сделать вручную, используя метод `Добавить()`, но это не удобно. При добавлении нового значения можно забыть добавить какой нибудь из вариантов.

Другой способ - хранить варианты значений в массивах и самостоятельно собирать комбинации, но это не очень красиво.

## Вариант реализации новой функциональности
Реализовать метод, который на вход получает массивы из возможных значений и генерирует их комбинацию.
```bsl
Значения1 = ЮТКоллекции.ЗначениеВМассиве(Истина, Ложь);
Значения2 = ЮТКоллекции.ЗначениеВМассиве(1, 2);

Варианты = ЮТест.Варианты()
    .ДобавитьКомбинацию(Значения1, Значения2)
    .СписокВариантов();
```
На выходе будет сгенерировано 4 варианта:
- Истина, 1
- Истина, 2
- Ложь, 1
- Ложь, 2

**Comment by alkoleft** [comment]
Предложенный выше вариант реализован в модуле тестовых данных, но он не совместим с механизмом вариантов, скрестить их вместе хорошая идея.

По генерации комбинаций давно уже мысли крутятся, пора начинать делать.

**Comment by 1cgh** [comment]
Как дополнительную опцию еще можно предусмотреть генерацию вариантов для попарного тестирования (pairwise).
Наглядный пример: https://pairwise.teremokgames.com/

**Comment by alkoleft** [comment]
@1cgh Алгоритм бы еще, пока я знаю только https://github.com/microsoft/pict
