### ISSUE TITLE
Добавить возможность для функций при использовании утверждений получать результат их выполнения

### ISSUE THREAD

**Issue by ViktorErmakov** [bia-technologies/yaxunit#35]
Когда я хочу проверять функцию и полученный результат, то мне приходится как бы дважды вызывать ее, один раз для проверки что не выбрасывается исключение, второй раз что бы результат обработать.
Подумать на возможность при использовании утверждений получать как то результат выполнения функции сразу.
Возможно уже что то есть, но в документации я не нашел.

![image](https://user-images.githubusercontent.com/39617680/215492761-7117dda9-feb0-43d7-908f-79abe9e665e5.png)

**Comment by alkoleft** [comment]
Сталкивался с подобной необходимостью.

Но в большинстве случаев проверку выполненности метода делать не нужно, нужно проверять результат метода.
В редких кейсах надо проверять и то, и то.
Если метод выбросит исключение, то это все равно отразиться в отчете.

Именно проверку отсутствия или наличия исключений делаю в случаях когда проверяю падения метода. Например, у меня есть метод чтения json из файла, при различных наборах параметров я должен ловить различные ошибки (отсутствие файла, невалидный json и тд), которые проверю.

**Comment by alkoleft** [comment]
Действительно ли вам необходимо проверять в вашем тесте и наличие исключений и результат метода?

**Comment by ViktorErmakov** [comment]
Спасибо за совет. Думаю тогда можно обойтись да. Вообще не хватает чата где можно задавать вопросы если что то не понятно, что бы тут не сорить)) Я сейчас целую библиотеку пытаюсь покрыть тестами с помощью инструмента. Спасибо!

**Comment by theshadowco** [comment]
https://t.me/BIAOpenTools/12

Приходите
