### ISSUE TITLE
При попытке запустить тестовый набор из описания Readme выдает ошибку 

### ISSUE THREAD

**Issue by BlizD** [bia-technologies/yaxunit#4]
Добрый день.

При попытке запустить тестовый набор из описания Readme выдает ошибку 

`Преобразование значения к типу Число не может быть выполнено
{YAXUNIT ОбщийМодуль.ЮТ_ТестыНовый.Модуль(82)}:Сообщить("Время выполнения теста: " + ТекущаяУниверсальнаяДатаВМиллисекундах() - Контекст.ВремяНачала);`

**Как вопроизвести**
Скопировал пример тестового набора из файла Readme
Запустил тесты
В файле отчета указана ошибка
`Преобразование значения к типу Число не может быть выполнено
{YAXUNIT ОбщийМодуль.ЮТ_ТестыНовый.Модуль(82)}:Сообщить("Время выполнения теста: " + ТекущаяУниверсальнаяДатаВМиллисекундах() - Контекст.ВремяНачала);`

При этом в режиме исполнения, ошибок не выдает
![image](https://user-images.githubusercontent.com/10989306/198523622-9655f653-f4c3-4456-9f1a-c79409df2e24.png)

**Comment by theshadowco** [comment]
Спасибо за фикс доки!
