### ISSUE TITLE
Мокирование HTTPСервисЗапрос

### ISSUE THREAD

**Issue by alkoleft** [bia-technologies/yaxunit#41]
Реализовать мок HTTPСервисЗапрос для тестирования http-сервисов без поднятия web сервера

**Comment by asosnoviy** [comment]
Внешняя обработка прекрасно справляется с мокированием входящего запроса.  
![image](https://user-images.githubusercontent.com/15638529/215964556-4435f842-ee8b-4afc-9007-8f2e1a8ecf63.png)

**Comment by alkoleft** [comment]
Да обработку и хочется, просто этот момент стандартизировать и иметь в движке.
