### ISSUE TITLE
Дублирование объявления функции ИмеетДлинуБольше

### ISSUE THREAD

**Issue by ilya2184** [bia-technologies/yaxunit#429]
https://github.com/bia-technologies/yaxunit/blob/0b5adaa9841edb48f6b7011fe36bdb6b43318acf/exts/yaxunit/src/CommonModules/%D0%AE%D0%A2%D0%A3%D1%82%D0%B2%D0%B5%D1%80%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F/Module.bsl#L1067

**Comment by ilya2184** [comment]
Вероятно ошибка слияния

**Comment by alkoleft** [comment]
> Вероятно ошибка слияния

Я думаю причина во мне)
Спасибо за исправление
