### ISSUE TITLE
В методе Провести() не учитывается уникальныйидентификатор для ссылки нового

### ISSUE THREAD

**Issue by AntonChausov** [bia-technologies/yaxunit#431]
в КонструкторОбъекта можно задать ссылку для нового объекта, передав в него ГУИД
ЮТест.Данные().КонструкторОбъекта().УстановитьСсылкуНового(ГУИД)

Но потом в методе Записать он учитывается, а в методе Провести - нет

![image](https://github.com/user-attachments/assets/e8a67417-41e7-4dc3-acd6-4c45119f2849)

**Comment by alexandr-yang** [comment]
@AntonChausov кажется у вас старая версия. Возможно раньше ошибка была, но ее уже поправили.
В актуально версии все норм
<img width="598" alt="image" src="https://github.com/user-attachments/assets/84797a48-5fd0-422e-ac61-8771b9b2343c">

**Comment by alkoleft** [comment]
Проблема не актуальна
