### ISSUE TITLE
Привести примеры к единому формату

### ISSUE THREAD

**Issue by igostv** [bia-technologies/yaxunit#44]
Сейчас можно встретить два варианта

1. Без дополнительных параметров:

https://github.com/bia-technologies/yaxunit/blob/7ae5a452f3f768a9fb8c09745d8bb3c98a7d45ac/%D0%A2%D0%B5%D1%81%D1%82%D1%8B%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80/src/CommonModules/%D0%9E%D0%9C_%D0%9C%D0%BE%D0%BA%D0%B8%D1%82%D0%BE/Module.bsl#L21

2. С дополнительными параметрами:

https://github.com/bia-technologies/yaxunit/blob/ba3bdf8c4ad7d2d7d5266e90f57671a82aa5245c/%D0%A2%D0%B5%D1%81%D1%82%D1%8B%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80/src/CommonModules/%D0%9E%D0%9C_%D0%AE%D0%A2%D0%A2%D0%B5%D1%81%D1%82%D1%8B/Module.bsl#L25

Обработка такой ситуации требует двойного вызова, стр. 77 и стр. 88.

https://github.com/bia-technologies/yaxunit/blob/7ae5a452f3f768a9fb8c09745d8bb3c98a7d45ac/exts/yaxunit/src/CommonModules/%D0%AE%D0%A2%D0%A7%D0%B8%D1%82%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/Module.bsl#L76-L89

**Comment by alkoleft** [comment]
Изначально закладывалось использование в тестах `ДополнительныеПараметры`, но пока эта идея так и не нашла реализации.

@theshadowco Предлагаю удалить такой вариант сигнатуры метода (в ближайшем релизе задеприкейтить)
