### ISSUE TITLE
Ошибка "Использование синх. методов на клиенте запрещено

### ISSUE THREAD

**Issue by KrapivinAndrey** [bia-technologies/yaxunit#45]
Версия: 23.01.0
Конфигурация: Чистая база
Платформа: 8.3.22.1750

При открытии Сформировать настройки ошибка на использование метода Поток.Закрыть()

![image](https://user-images.githubusercontent.com/586025/217506739-8f83eca7-9b9a-4262-b913-7b144f7bdf48.png)

![image](https://user-images.githubusercontent.com/586025/217506763-ee697b9c-0d6f-4b1a-ab64-4c12d6088bad.png)

**Comment by igostv** [comment]
В #21 просто отказались от операции с синхронным вызовом.
Но осталась ошибка если формируется отчет в junit, есть синхронные вызовы при записи файла (проверка, что путь к отчету это каталог).
Я уже даже PR почти отправил, но потом решил, что на данном этапе: `Это не баг, а фича!`
И т.к. я использовал механизм обещаний, то платформа требуется минимум 8.3.18 версии.
https://github.com/bia-technologies/yaxunit/blob/4a7abf319e560e7ba302a23f2ab88e431aff116b/exts/yaxunit/DT-INF/PROJECT.PMF#L2

Можно в документации написать, что режим использования синхронных вызовов расширений должен быть в значении "Использовать".
Или что скажут мейнтейнеры? Переходим на Асинх?

**Comment by theshadowco** [comment]
на асинх пока не переходим, т.к. поддержка 10-й версии нам нужна.

**Comment by KrapivinAndrey** [comment]
можно ж не асинх а Начать... и тд

**Comment by theshadowco** [comment]
ага

**Comment by alkoleft** [comment]
Для поддержки асинхоронных операций надо много чего переделать.

Ну или заложится на то что в тонком клиенте они выполняются последовательно

**Comment by L32GIT** [comment]
Ошибка, указанная в #21 как исправленная, по факту не исправлена.
Версия: 23.01.0
Стек при запуске единственного тривиального теста:

```
Использование синхронных методов на клиенте запрещено!
{YAXUNIT ОбщийМодуль.ЮТОбщий.Модуль(650)}:	Возврат Файл.Существует() И Файл.ЭтоКаталог();
{YAXUNIT ОбщийМодуль.ЮТОтчет.Модуль(95)}:	Если ЮТОбщий.ЭтоКаталог(ПутьКОтчету) Тогда
{YAXUNIT ОбщийМодуль.ЮТОтчет.Модуль(50)}:	ИмяФайлаОтчета = ИмяФайлаОтчета(Модуль, ПараметрыЗапуска);
{YAXUNIT ОбщийМодуль.ЮТИсполнитель.Модуль(79)}:	ЮТОтчет.СформироватьОтчет(РезультатыТестирования, Параметры);
{YAXUNIT МодульУправляемогоПриложения(38)}:	ЮТИсполнитель.ВыполнитьМодульноеТестирование();
```

**Comment by alkoleft** [comment]
@L32GIT Ошибка из #21 исправлена!

Но подобных ошибок еще хватает, как оказалось. Спасибо за пополнение коллекции.
