### ISSUE TITLE
Перезапуск тестов после запуска из конфигуратора

### ISSUE THREAD

**Issue by antonsm2011** [bia-technologies/yaxunit#49]
Как я делаю:
1. Запускаю из конфигуратора через F5 прогон всех тестов.
2. Вижу ошибку. 
3. Ставлю точку останова в нужном месте. 
4. Перезапускаю по F5, чтобы остановиться по точке останова.

В итоге очень не хватает какой-нибудь кнопки, чтобы не делать п.4.
Чтобы без перезапуска по F5 заново все тесты запустить и остановиться на точке останова.

Например, сделать как в EDT (запустить упавшие, повторно прогнать по имеющейся конфигурации запуска, запустить конкретный тест).
![2023-02-09_18-07-39](https://user-images.githubusercontent.com/12731230/217870946-5e756e8c-97b6-4176-92aa-df7c0992c272.png)

**Comment by alexandr-yang** [comment]
Может есть смысл сделать не только перезапуск тестов, но и полноценный запуск из режима предприятия?

Что-то похожее на ADD. Открываем встроенную обработку, нажимаем кнопку "Заполнить список тестов". И дальше выбираем какой тест (или группу тестов, или вообще все тесты) запустить.

**Comment by antonsm2011** [comment]
> Может есть смысл сделать не только перезапуск тестов, но и полноценный запуск из режима предприятия?

Не уверен, что полноценный запуск из режима предприятия прямо нужен.
И не могу сказать, насколько было бы это удобно или полезно.
А вот прогон тестов при запуске отладки из конфигуратора- это очень удобно.

**Comment by sulfur17** [comment]
@alkoleft а ты уже [начал](https://github.com/bia-technologies/yaxunit/commits/feature/49) по этой задаче работать?

**Comment by alkoleft** [comment]
> @alkoleft а ты уже [начал](https://github.com/bia-technologies/yaxunit/commits/feature/49) по этой задаче работать?

Начал немного, скоро выложу, а то я там начал накидывать лишнего, тестов формы захотел)
