### ISSUE TITLE
Реализовать возможность продолжать работу в ИБ с подключенным расширением, в котором задействован Мокито

### ISSUE THREAD

**Issue by ovcharenko-di** [bia-technologies/yaxunit#57]
## Дано
Подключенное к базе расширение yaxunit, в которое заимствован метод общего модуля, для которого выполняется АнализВызова() с продолжением выполнения (см. скриншот 1).

## Проблема
При вызове этого метода вне Мокито, например, при обычной работе в базе, возникает ошибка (см. скриншот 2).

## Желаемое поведение
При вызове этого метода в ходе обычной работы пользователя вызов заимствованного метода не должен приводить к ошибке. Как вариант, можно при отсутствии настроек вывести некое сообщение пользователю и вернуть ПрерватьВыполнение = Ложь

![image](https://user-images.githubusercontent.com/24920942/230444157-e2e76b9a-384f-4474-952a-5525ee508b9d.png)

![image](https://user-images.githubusercontent.com/24920942/230444053-16f48718-5792-4b8a-8e61-8d11175b6844.png)

**Comment by alkoleft** [comment]
Уточни, ошибка возникает когда ты просто работаешь с базой 1с (при этом тесты ты не трогаешь), в которой загружено тестовое расширение.
Или ты с ней работает после выполнения тестов (запустил тест и не закрываю предприятия продолжаешь что-то делать)?

**Comment by ovcharenko-di** [comment]
@alkoleft последний вариант
