### ISSUE TITLE
Как то можно получить форму со статистикой выполнения тестов в 1с Предприятии?

### ISSUE THREAD

**Issue by BlizD** [bia-technologies/yaxunit#6]
Добрый день.

Как то можно получить форму со статистикой выполнения тестов в 1с Предприятии?
По аналогии как показывается в EDT?
![image](https://user-images.githubusercontent.com/10989306/198527006-b355f8b1-0cd6-46ca-8e5c-4371f23ae5af.png)

**Comment by theshadowco** [comment]
При разработке без ЕДТ? Пока только просмотром junit отчета. 
Нужна форма? Опишите сценарий: как было бы удобно ее вызывать\получать результат

**Comment by BlizD** [comment]
>При разработке без ЕДТ?

Да, без EDT

>Нужна форма? Опишите сценарий: как было бы удобно ее вызывать\получать результат

В идеале открывается похожая форма как в EDT сразу после выполнения тестов в режиме предприятия 1с Предприятия.

**Comment by BlizD** [comment]
Как первое приближение к этой форме можно было бы сделать следующее:

Поля на форме
* Количество выполненных тестов;
* Количество ошибочно выполненных тестов
* Количество успешно выполненных тестов

Картинка или полоска "Зеленый" и "Красный".
Если Зеленый - значит все ок
Если Красный - значит есть проблема.

Плюс ссылка на файл отчета.

**Comment by asosnoviy** [comment]
Плюсану, без результата  подсадить коллег с конфигуратором не выйдет. 
Имхо можно просмоторщик junita в html затащить.

**Comment by theshadowco** [comment]
@asosnoviy @nixel2007 ЖВПР?

**Comment by theshadowco** [comment]
https://lotterfriends.github.io/online-junit-parser/junit_parser.js

**Comment by nixel2007** [comment]
я мимо крокодил

**Comment by theshadowco** [comment]
![image](https://user-images.githubusercontent.com/9591731/201458329-455a86b7-8cd5-4230-869d-4ff4d68409d5.png)
