### ISSUE TITLE
Работа функции "Фикция" в тестовых данных

### ISSUE THREAD

**Issue by Sicyro** [bia-technologies/yaxunit#75]
В функции фикция заявлен параметр "Реквизиты" который судя по описанию необходим чтобы в него передавали структуру заполняемых полей создаваемого объекта. Но при передаче, заполнение не происходит и судя по функции параметр ни где не используется. 
![image](https://user-images.githubusercontent.com/91005913/235876365-746ccc00-d8cc-4fb5-86a9-32b02fae563a.png)
Возможно ли добавление такой функции?

**Comment by alkoleft** [comment]
Конечно возможно, этот параметр задумывался для сокращения клиент-серверного взаимодействия и использования вложенного конструктора. Но, что-то пошло не так

Сейчас можно воспользоваться отдельным вызовом конструктора для решения проблемы.

```bsl
ОсновнойЗайм = ЮТест.Данные().КонструкторОбъекта().Фикция("НомерДоговора").Записать();

...
Конструктор.Установить("ОсновнойЗайм", ОсновнойЗайм);
...
```

Еще, при работе с конструктором есть одна особенность - #55
