### ISSUE TITLE
Выдается ошибка при выполнении тестов Значение не является значением объектного типа (Уровень) 

### ISSUE THREAD

**Issue by BlizD** [bia-technologies/yaxunit#8]
Релиз: 22.11.0
Выдается ошибка при выполнении тестов
`Значение не является значением объектного типа (Уровень)
{YAXUNIT ОбщийМодуль.ЮТИсполнитель.Модуль(101)}:	ЮТКонтекст.КонтекстИсполнения().Уровень = Уровни.Модуль;
{YAXUNIT ОбщийМодуль.ЮТИсполнительСервер.Модуль(44)}:	Возврат ЮТИсполнитель.ВыполнитьГруппуНаборовТестов(Наборы, ТестовыйМодуль);
{YAXUNIT ОбщийМодуль.ЮТИсполнитель.Модуль(60)}:		Результат = ЮТИсполнительСервер.ВыполнитьГруппуНаборовТестов(КатегорииНаборов.Серверные, ТестовыйМодуль);
{YAXUNIT МодульУправляемогоПриложения(38)}:	ЮТИсполнитель.ВыполнитьМодульноеТестирование();`

Файл настроек 
![image](https://user-images.githubusercontent.com/10989306/201643385-6a138d42-36c4-4446-a989-661fa69a8817.png)

Команда запуска
RunUnitTests=C:\1С\IvaRep\junit\test-config.json

В релизе 22.10.0 - тесты выполнялись без ошибок.
Различия между 22.11.0 и 22.10.0 только добавлен мной общий модуль "ив_Тесты_Проверка"

**Comment by BlizD** [comment]
Отбой заработало само
![image](https://user-images.githubusercontent.com/10989306/201644106-7b073c14-4a88-4f0e-b573-321a45a0e9c5.png)

**Comment by theshadowco** [comment]
Ну вот :)
