### ISSUE TITLE
Нужна генерация валидных бизнес данных

### ISSUE THREAD

**Issue by petypen** [bia-technologies/yaxunit#80]
Нужна генерация валидных бизнес данных, например:
* ИНН
* Телефон
* Адрес
* Расчетный счет
* Штрихкод

**Comment by alkoleft** [comment]
@petypen Закрываем?

В #119  кажется все что нужно реализовали

**Comment by Daabramov** [comment]
> @petypen Закрываем?
> 
> В #119 кажется все что нужно реализовали

Нет адресов, телефонов и штрихкодов.
Но есть база для реализации.

**Comment by petypen** [comment]
@alkoleft Алексей, да закрывай.
