### ISSUE TITLE
При нажатии на кнопку "Сформировать настройки" выдается ошибка

### ISSUE THREAD

**Issue by BlizD** [bia-technologies/yaxunit#9]
При нажатии на кнопку "Сформировать настройки" выдается ошибка
`Ошибка инициализации модуля: YAXUNIT ОбщийМодуль.МокитоОбучение.Модуль
по причине:
{YAXUNIT ОбщийМодуль.МокитоОбучение.Модуль(56,9)}: Процедура или функция с указанным именем уже определена (Наблюдать)
Функция <<?>>Наблюдать(ИмяМетода, ПараметрыВызова = Неопределено) Экспорт
{YAXUNIT ОбщийМодуль.МокитоОбучение.Модуль(81,10)}: Обращение к процедуре как к функции (Наблюдать)
	Возврат <<?>>Наблюдать(ИмяМетода, ПараметрыВызова);`

**Как воспроизвести**
1. Настроить выдачу формы результата тестирования при работе с конфигуратором;
1. После запуска в режиме исполнения в форме нажать "Сформировать настройки"

![image](https://user-images.githubusercontent.com/10989306/201646769-81c8078e-fde4-44d4-adac-cefec81c380b.png)
Судя по количеству вызовов там какой бесконечный цикл/рекурсия, т.к. количество вызовов растет без остановки до появления ошибки.

![image](https://user-images.githubusercontent.com/10989306/201647003-52b4be9f-a515-4f86-bbc4-ffdf91c2c684.png)

Файл настроек
![image](https://user-images.githubusercontent.com/10989306/201647207-96428a4f-0762-45b9-b546-e8c07825035e.png)

**Comment by alkoleft** [comment]
@BlizD Не воспроизвелось
Судя по всему у тебя используются моки?

Попробуй добавить `ОбновитьПовторноИспользуемыеЗначения();` вот так

![image](https://user-images.githubusercontent.com/13838250/201648507-335cbee9-39ac-4465-9faa-1728c05f4000.png)

**Comment by BlizD** [comment]
>Судя по всему у тебя используются моки?

Нет, не используются.

>Попробуй добавить ОбновитьПовторноИспользуемыеЗначения(); вот так

Добавил, не помогло

![image](https://user-images.githubusercontent.com/10989306/201649538-994c65dd-493b-4ec1-a5e9-beaee18d32f0.png)

**Comment by BlizD** [comment]
Вспомнил, у меня такая же ошибка выдавалась при первом запуске в версии 22.10.0

Пока в файле настроек не прописал, что нужно смотреть только мой модуль с тестами.
![image](https://user-images.githubusercontent.com/10989306/201650915-88105d6c-8e74-4cc1-9035-43008e370743.png)

**Comment by alkoleft** [comment]
`Процедура или функция с указанным именем уже определена (Наблюдать)`

А у тебя случайно нет такого глобального метода?

**Comment by EvgSychev** [comment]
То же самое происходит при запуске приложения из едт. Падаем с ошибкой, что такой метод, Наблюдать, уже определен. При запуске приложения из конфигуратора, с подключенным расширением, такой ошибки нет. 
![image](https://user-images.githubusercontent.com/81824263/201667123-7c18ce9e-15dc-44fa-8d36-bacc1cce702c.png)

**Comment by EvgSychev** [comment]
Забавно, переименовал Наблюдать в _Наблюдать. Словил следующую ошибку.
![image](https://user-images.githubusercontent.com/81824263/201669671-34f7db08-f054-419b-b010-e7d3d7911d81.png)

**Comment by alkoleft** [comment]
Получается метод есть. Вопрос откуда он. @EvgSychev Попробуй найти его, ctrl+click в едт, Ф12 в конфигураторе...

**Comment by EvgSychev** [comment]
Найдено :)
![image](https://user-images.githubusercontent.com/81824263/201670467-85127a1f-6a56-4087-99fd-9e5dacba78b5.png)

**Comment by alkoleft** [comment]
Штош, пока могу предложить выкинуть мокито (просто удалить 4 модуля), если конечно им не пользуешься)
